server:
  port: 8090

spring:
  application:
    name: POST-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/postService?createDatabaseIfNotExist=true
    username: root
    password: rootroot

  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka