server:
  port: 8090

spring:
  application:
    name: POST-SERVICE

# MYSQL CONFIG
  datasource:
    url: jdbc:mysql://localhost:3306/postService?createDatabaseIfNotExist=true
    username: root
    password: rootroot

  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


#KAFKA CONFIG
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#EUREKA SERVER CONFIG
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


#EVENTS
post:
  topic:
    name:
      create: postCreatedEvent
      update: postUpdatedEvent
      delete: postDeletedEvent