server:
  port: 8092

spring:
  application:
    name: QUERY-SERVICE

# MYSQL CONFIG
  datasource:
    url: jdbc:mysql://localhost:3306/queryService?createDatabaseIfNotExist=true
    username: root
    password: rootroot

  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


# KAFKA CONFIG
  kafka:
    consumer:
      group-id: query-service
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'


# EUREKA SERVER CONFIG
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# EVENTS
post:
  topic:
    name:
      create: postCreatedEvent
      update: postUpdatedEvent
      delete: postDeletedEvent

comment:
  topic:
    name:
      create: commentCreatedEvent
      update: commentUpdatedEvent
      delete: commentDeletedEvent

